### PR TITLE
Bump go verion to 1.17

### PR DESCRIPTION
**Pull request by pigletfly**
The depend in github ci workflow is already go 1.17.x

### CODE REVIEW

**Comment by pigletfly** [comment]
and also bump actions/setup-go actions/checkout  golangci/golangci-lint-action to v3.Otherwise, there is a chance to use cached go1.18 env even we pinned go version to 1.17.x

**Review by estesp — APPROVED** [review]
LGTM

**Comment by fuweid** [comment]
@pigletfly could you use real name in commit signoff? Thanks

`Signed-off-by: pigletfly <wangbing.adam@gmail.com>`

**Review by mikebrow — APPROVED** [review]
LGTM

**Comment by pigletfly** [comment]
> 

done

**Review by fuweid — APPROVED** [review]

**Pull request merged**
