### PR TITLE
go.mod: github.com/containernetworking/cni v1.0.1

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Review by mikebrow — APPROVED** [review]
LGTM
and.. we are getting ahead of the version of cni used in k8s, just something to consider as we need to try and keep compat with the plugins used in other network components in the master and worker nodes.

**Review by fuweid — APPROVED** [review]
LGTM

**Comment by AkihiroSuda** [comment]
released https://github.com/containerd/go-cni/releases/tag/v1.1.0

**Comment by mikebrow** [comment]
note... until cni adds a converter here for 1.0.1 we can't move up the version we are using in containerd or we won't be able to do a live update of containerd.. because when you try to remove the pod and it goes to destroy the network.. you'll get one of these errors:
```
FATA[0000] stopping the pod sandbox "9b": rpc error: code = Unknown desc = failed to destroy network for sandbox "9b068ec35dfaffe5e92287db5d24731a30569d13ab88addfeb07361956d407e4": failed to get network "containerd-net" cached result: failed to convert cached result to config version "1.0.1": no converter for CNI result version 0.4.0 to 1.0.1 
```

here's the list of existing converters:  https://github.com/containernetworking/cni/blob/master/pkg/types/100/types.go#L43

**Pull request merged**
