### PR TITLE
Minor cleanup with concurrency and locking

### PR DESCRIPTION
**Pull request by abhi**
Signed-off-by: Abhinandan Prativadi <abhi@docker.com>

### CODE REVIEW

**Comment by Random-Liu** [comment]
I understand embedded RLock has no problem, but I still prefer having a separate `status` helper function which doesn't grab a lock, and change all public functions to use it.

**Comment by abhi** [comment]
@Random-Liu yes. The only reason is between status check and the actual setup we might have an update so It might be better to avoid the race by the embedded RLock is what I think.

**Comment by Random-Liu** [comment]
@abhi I mean you can have an internal `status` function which doesn't have lock, and change `Status`, `Setup`, and `Remove` to use the internal `status`. In this way, you don't need embedded RLock and get the same result.

**Comment by abhi** [comment]
@Random-Liu done

**Comment by Random-Liu** [comment]
LGTM

**Pull request merged**
